// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: model/config.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inbounds  []*InboundObject  `protobuf:"bytes,1,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Outbounds []*OutboundObject `protobuf:"bytes,2,rep,name=outbounds,proto3" json:"outbounds,omitempty"`
	Api       *ApiObject        `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	Routing   *RoutingObject    `protobuf:"bytes,4,opt,name=routing,proto3" json:"routing,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetInbounds() []*InboundObject {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *Config) GetOutbounds() []*OutboundObject {
	if x != nil {
		return x.Outbounds
	}
	return nil
}

func (x *Config) GetApi() *ApiObject {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Config) GetRouting() *RoutingObject {
	if x != nil {
		return x.Routing
	}
	return nil
}

type InboundObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string                        `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port     uint32                        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Listen   string                        `protobuf:"bytes,3,opt,name=listen,proto3" json:"listen,omitempty"`
	Settings *any.Any                      `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	Tag      string                        `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Sniffing *InboundObject_SniffingObject `protobuf:"bytes,6,opt,name=sniffing,proto3" json:"sniffing,omitempty"`
}

func (x *InboundObject) Reset() {
	*x = InboundObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InboundObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundObject) ProtoMessage() {}

func (x *InboundObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundObject.ProtoReflect.Descriptor instead.
func (*InboundObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{1}
}

func (x *InboundObject) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundObject) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InboundObject) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *InboundObject) GetSettings() *any.Any {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *InboundObject) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundObject) GetSniffing() *InboundObject_SniffingObject {
	if x != nil {
		return x.Sniffing
	}
	return nil
}

type OutboundObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Tag      string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Settings *any.Any `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *OutboundObject) Reset() {
	*x = OutboundObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboundObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundObject) ProtoMessage() {}

func (x *OutboundObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundObject.ProtoReflect.Descriptor instead.
func (*OutboundObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{2}
}

func (x *OutboundObject) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OutboundObject) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundObject) GetSettings() *any.Any {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ApiObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag      string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Services []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ApiObject) Reset() {
	*x = ApiObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiObject) ProtoMessage() {}

func (x *ApiObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiObject.ProtoReflect.Descriptor instead.
func (*ApiObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{3}
}

func (x *ApiObject) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ApiObject) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type RoutingObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*RoutingObject_RuleObject `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *RoutingObject) Reset() {
	*x = RoutingObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingObject) ProtoMessage() {}

func (x *RoutingObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingObject.ProtoReflect.Descriptor instead.
func (*RoutingObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{4}
}

func (x *RoutingObject) GetRules() []*RoutingObject_RuleObject {
	if x != nil {
		return x.Rules
	}
	return nil
}

type InboundObject_SniffingObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled      bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DestOverride []string `protobuf:"bytes,2,rep,name=destOverride,proto3" json:"destOverride,omitempty"`
}

func (x *InboundObject_SniffingObject) Reset() {
	*x = InboundObject_SniffingObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InboundObject_SniffingObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundObject_SniffingObject) ProtoMessage() {}

func (x *InboundObject_SniffingObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundObject_SniffingObject.ProtoReflect.Descriptor instead.
func (*InboundObject_SniffingObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InboundObject_SniffingObject) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InboundObject_SniffingObject) GetDestOverride() []string {
	if x != nil {
		return x.DestOverride
	}
	return nil
}

type RoutingObject_RuleObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain      []string `protobuf:"bytes,1,rep,name=domain,proto3" json:"domain,omitempty"`
	Ip          []string `protobuf:"bytes,2,rep,name=ip,proto3" json:"ip,omitempty"`
	Port        string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Network     string   `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Source      []string `protobuf:"bytes,5,rep,name=source,proto3" json:"source,omitempty"`
	InboundTag  []string `protobuf:"bytes,6,rep,name=inboundTag,proto3" json:"inboundTag,omitempty"`
	Protocol    []string `protobuf:"bytes,7,rep,name=protocol,proto3" json:"protocol,omitempty"`
	Attrs       string   `protobuf:"bytes,8,opt,name=attrs,proto3" json:"attrs,omitempty"`
	OutboundTag string   `protobuf:"bytes,9,opt,name=outboundTag,proto3" json:"outboundTag,omitempty"`
	BalancerTag string   `protobuf:"bytes,10,opt,name=balancerTag,proto3" json:"balancerTag,omitempty"`
	Type        string   `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *RoutingObject_RuleObject) Reset() {
	*x = RoutingObject_RuleObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingObject_RuleObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingObject_RuleObject) ProtoMessage() {}

func (x *RoutingObject_RuleObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingObject_RuleObject.ProtoReflect.Descriptor instead.
func (*RoutingObject_RuleObject) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RoutingObject_RuleObject) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RoutingObject_RuleObject) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *RoutingObject_RuleObject) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RoutingObject_RuleObject) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *RoutingObject_RuleObject) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RoutingObject_RuleObject) GetInboundTag() []string {
	if x != nil {
		return x.InboundTag
	}
	return nil
}

func (x *RoutingObject_RuleObject) GetProtocol() []string {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *RoutingObject_RuleObject) GetAttrs() string {
	if x != nil {
		return x.Attrs
	}
	return ""
}

func (x *RoutingObject_RuleObject) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RoutingObject_RuleObject) GetBalancerTag() string {
	if x != nil {
		return x.BalancerTag
	}
	return ""
}

func (x *RoutingObject_RuleObject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_model_config_proto protoreflect.FileDescriptor

var file_model_config_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x30, 0x0a, 0x08, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x6e, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x69, 0x6e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x09, 0x6f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x70,
	0x69, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x2e, 0x0a, 0x07,
	0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xac, 0x02, 0x0a,
	0x0d, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x30, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x3f, 0x0a, 0x08, 0x73, 0x6e,
	0x69, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x53, 0x6e, 0x69, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x08, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x1a, 0x4e, 0x0a, 0x0e, 0x53,
	0x6e, 0x69, 0x66, 0x66, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x4f,
	0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x65, 0x73, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x70, 0x0a, 0x0e, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x30, 0x0a, 0x08, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x39, 0x0a,
	0x09, 0x41, 0x70, 0x69, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xed, 0x02, 0x0a, 0x0d, 0x52, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x1a, 0xa4, 0x02, 0x0a, 0x0a, 0x52, 0x75, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74,
	0x74, 0x72, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x61, 0x67, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x54,
	0x61, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x54, 0x61,
	0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_config_proto_rawDescOnce sync.Once
	file_model_config_proto_rawDescData = file_model_config_proto_rawDesc
)

func file_model_config_proto_rawDescGZIP() []byte {
	file_model_config_proto_rawDescOnce.Do(func() {
		file_model_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_config_proto_rawDescData)
	})
	return file_model_config_proto_rawDescData
}

var file_model_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_model_config_proto_goTypes = []interface{}{
	(*Config)(nil),                       // 0: model.Config
	(*InboundObject)(nil),                // 1: model.InboundObject
	(*OutboundObject)(nil),               // 2: model.OutboundObject
	(*ApiObject)(nil),                    // 3: model.ApiObject
	(*RoutingObject)(nil),                // 4: model.RoutingObject
	(*InboundObject_SniffingObject)(nil), // 5: model.InboundObject.SniffingObject
	(*RoutingObject_RuleObject)(nil),     // 6: model.RoutingObject.RuleObject
	(*any.Any)(nil),                      // 7: google.protobuf.Any
}
var file_model_config_proto_depIdxs = []int32{
	1, // 0: model.Config.inbounds:type_name -> model.InboundObject
	2, // 1: model.Config.outbounds:type_name -> model.OutboundObject
	3, // 2: model.Config.api:type_name -> model.ApiObject
	4, // 3: model.Config.routing:type_name -> model.RoutingObject
	7, // 4: model.InboundObject.settings:type_name -> google.protobuf.Any
	5, // 5: model.InboundObject.sniffing:type_name -> model.InboundObject.SniffingObject
	7, // 6: model.OutboundObject.settings:type_name -> google.protobuf.Any
	6, // 7: model.RoutingObject.rules:type_name -> model.RoutingObject.RuleObject
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_model_config_proto_init() }
func file_model_config_proto_init() {
	if File_model_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InboundObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutboundObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InboundObject_SniffingObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingObject_RuleObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_config_proto_goTypes,
		DependencyIndexes: file_model_config_proto_depIdxs,
		MessageInfos:      file_model_config_proto_msgTypes,
	}.Build()
	File_model_config_proto = out.File
	file_model_config_proto_rawDesc = nil
	file_model_config_proto_goTypes = nil
	file_model_config_proto_depIdxs = nil
}
