// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: model/shadowsocks.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Protocol int32

const (
	Protocol_Shadowsocks   Protocol = 0
	Protocol_Blackhole     Protocol = 1
	Protocol_Dokodemo_door Protocol = 2
	Protocol_Freedom       Protocol = 3
	Protocol_HTTP          Protocol = 4
	Protocol_MTProto       Protocol = 5
	Protocol_Socks         Protocol = 6
	Protocol_VMess         Protocol = 7
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "Shadowsocks",
		1: "Blackhole",
		2: "Dokodemo_door",
		3: "Freedom",
		4: "HTTP",
		5: "MTProto",
		6: "Socks",
		7: "VMess",
	}
	Protocol_value = map[string]int32{
		"Shadowsocks":   0,
		"Blackhole":     1,
		"Dokodemo_door": 2,
		"Freedom":       3,
		"HTTP":          4,
		"MTProto":       5,
		"Socks":         6,
		"VMess":         7,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_model_shadowsocks_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_model_shadowsocks_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{0}
}

type Method int32

const (
	Method_aes_256_cfb       Method = 0
	Method_aes_128_cfb       Method = 1
	Method_chacha20          Method = 2
	Method_chacha20_ietf     Method = 3
	Method_aes_256_gcm       Method = 4
	Method_aes_128_gcm       Method = 5
	Method_chacha20_poly1305 Method = 6
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "aes_256_cfb",
		1: "aes_128_cfb",
		2: "chacha20",
		3: "chacha20_ietf",
		4: "aes_256_gcm",
		5: "aes_128_gcm",
		6: "chacha20_poly1305",
	}
	Method_value = map[string]int32{
		"aes_256_cfb":       0,
		"aes_128_cfb":       1,
		"chacha20":          2,
		"chacha20_ietf":     3,
		"aes_256_gcm":       4,
		"aes_128_gcm":       5,
		"chacha20_poly1305": 6,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_model_shadowsocks_proto_enumTypes[1].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_model_shadowsocks_proto_enumTypes[1]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{1}
}

type ShadowsocksInboundConfigurationObject_Network int32

const (
	ShadowsocksInboundConfigurationObject_tcp     ShadowsocksInboundConfigurationObject_Network = 0
	ShadowsocksInboundConfigurationObject_udp     ShadowsocksInboundConfigurationObject_Network = 1
	ShadowsocksInboundConfigurationObject_tcp_udp ShadowsocksInboundConfigurationObject_Network = 2
)

// Enum value maps for ShadowsocksInboundConfigurationObject_Network.
var (
	ShadowsocksInboundConfigurationObject_Network_name = map[int32]string{
		0: "tcp",
		1: "udp",
		2: "tcp_udp",
	}
	ShadowsocksInboundConfigurationObject_Network_value = map[string]int32{
		"tcp":     0,
		"udp":     1,
		"tcp_udp": 2,
	}
)

func (x ShadowsocksInboundConfigurationObject_Network) Enum() *ShadowsocksInboundConfigurationObject_Network {
	p := new(ShadowsocksInboundConfigurationObject_Network)
	*p = x
	return p
}

func (x ShadowsocksInboundConfigurationObject_Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShadowsocksInboundConfigurationObject_Network) Descriptor() protoreflect.EnumDescriptor {
	return file_model_shadowsocks_proto_enumTypes[2].Descriptor()
}

func (ShadowsocksInboundConfigurationObject_Network) Type() protoreflect.EnumType {
	return &file_model_shadowsocks_proto_enumTypes[2]
}

func (x ShadowsocksInboundConfigurationObject_Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShadowsocksInboundConfigurationObject_Network.Descriptor instead.
func (ShadowsocksInboundConfigurationObject_Network) EnumDescriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{0, 0}
}

type ShadowsocksInboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string                                        `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Method   Method                                        `protobuf:"varint,2,opt,name=method,proto3,enum=model.Method" json:"method,omitempty"`
	Password string                                        `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Level    uint32                                        `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Ota      bool                                          `protobuf:"varint,5,opt,name=ota,proto3" json:"ota,omitempty"`
	Network  ShadowsocksInboundConfigurationObject_Network `protobuf:"varint,6,opt,name=network,proto3,enum=model.ShadowsocksInboundConfigurationObject_Network" json:"network,omitempty"`
}

func (x *ShadowsocksInboundConfigurationObject) Reset() {
	*x = ShadowsocksInboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksInboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksInboundConfigurationObject) ProtoMessage() {}

func (x *ShadowsocksInboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksInboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksInboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{0}
}

func (x *ShadowsocksInboundConfigurationObject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShadowsocksInboundConfigurationObject) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_aes_256_cfb
}

func (x *ShadowsocksInboundConfigurationObject) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksInboundConfigurationObject) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ShadowsocksInboundConfigurationObject) GetOta() bool {
	if x != nil {
		return x.Ota
	}
	return false
}

func (x *ShadowsocksInboundConfigurationObject) GetNetwork() ShadowsocksInboundConfigurationObject_Network {
	if x != nil {
		return x.Network
	}
	return ShadowsocksInboundConfigurationObject_tcp
}

type ShadowsocksOutboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*ShadowsocksOutboundConfigurationObject_ServerObject `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *ShadowsocksOutboundConfigurationObject) Reset() {
	*x = ShadowsocksOutboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksOutboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksOutboundConfigurationObject) ProtoMessage() {}

func (x *ShadowsocksOutboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksOutboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksOutboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowsocksOutboundConfigurationObject) GetServers() []*ShadowsocksOutboundConfigurationObject_ServerObject {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ShadowsocksOutboundConfigurationObject_ServerObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Method   string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // Method
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Ota      bool   `protobuf:"varint,6,opt,name=ota,proto3" json:"ota,omitempty"`
	Level    uint32 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) Reset() {
	*x = ShadowsocksOutboundConfigurationObject_ServerObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksOutboundConfigurationObject_ServerObject) ProtoMessage() {}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksOutboundConfigurationObject_ServerObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksOutboundConfigurationObject_ServerObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetOta() bool {
	if x != nil {
		return x.Ota
	}
	return false
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_model_shadowsocks_proto protoreflect.FileDescriptor

var file_model_shadowsocks_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f,
	0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x22, 0xa2, 0x02, 0x0a, 0x25, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63, 0x6b, 0x73,
	0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x25, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6f, 0x74, 0x61, 0x12, 0x4e, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63, 0x6b, 0x73,
	0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x28, 0x0a, 0x07, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x07, 0x0a, 0x03, 0x74, 0x63, 0x70, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x75, 0x64, 0x70, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x74, 0x63, 0x70, 0x5f,
	0x75, 0x64, 0x70, 0x10, 0x02, 0x22, 0xaf, 0x02, 0x0a, 0x26, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77,
	0x73, 0x6f, 0x63, 0x6b, 0x73, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x54, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77,
	0x73, 0x6f, 0x63, 0x6b, 0x73, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x1a, 0xae, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6f, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2a, 0x77, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63,
	0x6b, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c,
	0x65, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x6f, 0x6b, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x5f,
	0x64, 0x6f, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x72, 0x65, 0x65, 0x64, 0x6f,
	0x6d, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x4d, 0x54, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x6f,
	0x63, 0x6b, 0x73, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x4d, 0x65, 0x73, 0x73, 0x10, 0x07,
	0x2a, 0x84, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x61,
	0x65, 0x73, 0x5f, 0x32, 0x35, 0x36, 0x5f, 0x63, 0x66, 0x62, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x61, 0x65, 0x73, 0x5f, 0x31, 0x32, 0x38, 0x5f, 0x63, 0x66, 0x62, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x63, 0x68, 0x61, 0x63, 0x68, 0x61, 0x32, 0x30, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x63,
	0x68, 0x61, 0x63, 0x68, 0x61, 0x32, 0x30, 0x5f, 0x69, 0x65, 0x74, 0x66, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x61, 0x65, 0x73, 0x5f, 0x32, 0x35, 0x36, 0x5f, 0x67, 0x63, 0x6d, 0x10, 0x04, 0x12,
	0x0f, 0x0a, 0x0b, 0x61, 0x65, 0x73, 0x5f, 0x31, 0x32, 0x38, 0x5f, 0x67, 0x63, 0x6d, 0x10, 0x05,
	0x12, 0x15, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x63, 0x68, 0x61, 0x32, 0x30, 0x5f, 0x70, 0x6f, 0x6c,
	0x79, 0x31, 0x33, 0x30, 0x35, 0x10, 0x06, 0x42, 0x07, 0x5a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_shadowsocks_proto_rawDescOnce sync.Once
	file_model_shadowsocks_proto_rawDescData = file_model_shadowsocks_proto_rawDesc
)

func file_model_shadowsocks_proto_rawDescGZIP() []byte {
	file_model_shadowsocks_proto_rawDescOnce.Do(func() {
		file_model_shadowsocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_shadowsocks_proto_rawDescData)
	})
	return file_model_shadowsocks_proto_rawDescData
}

var file_model_shadowsocks_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_model_shadowsocks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_shadowsocks_proto_goTypes = []interface{}{
	(Protocol)(0), // 0: model.Protocol
	(Method)(0),   // 1: model.Method
	(ShadowsocksInboundConfigurationObject_Network)(0),          // 2: model.ShadowsocksInboundConfigurationObject.Network
	(*ShadowsocksInboundConfigurationObject)(nil),               // 3: model.ShadowsocksInboundConfigurationObject
	(*ShadowsocksOutboundConfigurationObject)(nil),              // 4: model.ShadowsocksOutboundConfigurationObject
	(*ShadowsocksOutboundConfigurationObject_ServerObject)(nil), // 5: model.ShadowsocksOutboundConfigurationObject.ServerObject
}
var file_model_shadowsocks_proto_depIdxs = []int32{
	1, // 0: model.ShadowsocksInboundConfigurationObject.method:type_name -> model.Method
	2, // 1: model.ShadowsocksInboundConfigurationObject.network:type_name -> model.ShadowsocksInboundConfigurationObject.Network
	5, // 2: model.ShadowsocksOutboundConfigurationObject.servers:type_name -> model.ShadowsocksOutboundConfigurationObject.ServerObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_shadowsocks_proto_init() }
func file_model_shadowsocks_proto_init() {
	if File_model_shadowsocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_shadowsocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksInboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksOutboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksOutboundConfigurationObject_ServerObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_shadowsocks_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_shadowsocks_proto_goTypes,
		DependencyIndexes: file_model_shadowsocks_proto_depIdxs,
		EnumInfos:         file_model_shadowsocks_proto_enumTypes,
		MessageInfos:      file_model_shadowsocks_proto_msgTypes,
	}.Build()
	File_model_shadowsocks_proto = out.File
	file_model_shadowsocks_proto_rawDesc = nil
	file_model_shadowsocks_proto_goTypes = nil
	file_model_shadowsocks_proto_depIdxs = nil
}
