// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: model/shadowsocks.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ShadowsocksInboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Method   string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Level    uint32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Network  string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *ShadowsocksInboundConfigurationObject) Reset() {
	*x = ShadowsocksInboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksInboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksInboundConfigurationObject) ProtoMessage() {}

func (x *ShadowsocksInboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksInboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksInboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{0}
}

func (x *ShadowsocksInboundConfigurationObject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShadowsocksInboundConfigurationObject) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ShadowsocksInboundConfigurationObject) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksInboundConfigurationObject) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ShadowsocksInboundConfigurationObject) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ShadowsocksOutboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*ShadowsocksOutboundConfigurationObject_ServerObject `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *ShadowsocksOutboundConfigurationObject) Reset() {
	*x = ShadowsocksOutboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksOutboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksOutboundConfigurationObject) ProtoMessage() {}

func (x *ShadowsocksOutboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksOutboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksOutboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowsocksOutboundConfigurationObject) GetServers() []*ShadowsocksOutboundConfigurationObject_ServerObject {
	if x != nil {
		return x.Servers
	}
	return nil
}

type DokodemoInboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address        string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port           uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Network        string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Timeout        uint32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FollowRedirect bool   `protobuf:"varint,5,opt,name=followRedirect,proto3" json:"followRedirect,omitempty"`
	UserLevel      uint32 `protobuf:"varint,6,opt,name=userLevel,proto3" json:"userLevel,omitempty"`
}

func (x *DokodemoInboundConfigurationObject) Reset() {
	*x = DokodemoInboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DokodemoInboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DokodemoInboundConfigurationObject) ProtoMessage() {}

func (x *DokodemoInboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DokodemoInboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*DokodemoInboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{2}
}

func (x *DokodemoInboundConfigurationObject) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DokodemoInboundConfigurationObject) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DokodemoInboundConfigurationObject) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DokodemoInboundConfigurationObject) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *DokodemoInboundConfigurationObject) GetFollowRedirect() bool {
	if x != nil {
		return x.FollowRedirect
	}
	return false
}

func (x *DokodemoInboundConfigurationObject) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

type FreedomOutboundConfigurationObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainStrategy string `protobuf:"bytes,1,opt,name=domainStrategy,proto3" json:"domainStrategy,omitempty"`
	Redirect       string `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	UserLevel      uint32 `protobuf:"varint,3,opt,name=userLevel,proto3" json:"userLevel,omitempty"`
}

func (x *FreedomOutboundConfigurationObject) Reset() {
	*x = FreedomOutboundConfigurationObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreedomOutboundConfigurationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreedomOutboundConfigurationObject) ProtoMessage() {}

func (x *FreedomOutboundConfigurationObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreedomOutboundConfigurationObject.ProtoReflect.Descriptor instead.
func (*FreedomOutboundConfigurationObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{3}
}

func (x *FreedomOutboundConfigurationObject) GetDomainStrategy() string {
	if x != nil {
		return x.DomainStrategy
	}
	return ""
}

func (x *FreedomOutboundConfigurationObject) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *FreedomOutboundConfigurationObject) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

type StreamSettingsObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network      string                              `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Security     string                              `protobuf:"bytes,2,opt,name=security,proto3" json:"security,omitempty"`
	TlsSettings  *any.Any                            `protobuf:"bytes,3,opt,name=tlsSettings,proto3" json:"tlsSettings,omitempty"`
	TcpSettings  *any.Any                            `protobuf:"bytes,4,opt,name=tcpSettings,proto3" json:"tcpSettings,omitempty"`
	KcpSettings  *any.Any                            `protobuf:"bytes,5,opt,name=kcpSettings,proto3" json:"kcpSettings,omitempty"`
	WsSettings   *any.Any                            `protobuf:"bytes,6,opt,name=wsSettings,proto3" json:"wsSettings,omitempty"`
	HttpSettings *any.Any                            `protobuf:"bytes,7,opt,name=httpSettings,proto3" json:"httpSettings,omitempty"`
	QuicSettings *any.Any                            `protobuf:"bytes,8,opt,name=quicSettings,proto3" json:"quicSettings,omitempty"`
	DsSettings   *any.Any                            `protobuf:"bytes,9,opt,name=dsSettings,proto3" json:"dsSettings,omitempty"`
	Sockopt      *StreamSettingsObject_SockoptObject `protobuf:"bytes,10,opt,name=sockopt,proto3" json:"sockopt,omitempty"`
}

func (x *StreamSettingsObject) Reset() {
	*x = StreamSettingsObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamSettingsObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSettingsObject) ProtoMessage() {}

func (x *StreamSettingsObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSettingsObject.ProtoReflect.Descriptor instead.
func (*StreamSettingsObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{4}
}

func (x *StreamSettingsObject) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *StreamSettingsObject) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *StreamSettingsObject) GetTlsSettings() *any.Any {
	if x != nil {
		return x.TlsSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetTcpSettings() *any.Any {
	if x != nil {
		return x.TcpSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetKcpSettings() *any.Any {
	if x != nil {
		return x.KcpSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetWsSettings() *any.Any {
	if x != nil {
		return x.WsSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetHttpSettings() *any.Any {
	if x != nil {
		return x.HttpSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetQuicSettings() *any.Any {
	if x != nil {
		return x.QuicSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetDsSettings() *any.Any {
	if x != nil {
		return x.DsSettings
	}
	return nil
}

func (x *StreamSettingsObject) GetSockopt() *StreamSettingsObject_SockoptObject {
	if x != nil {
		return x.Sockopt
	}
	return nil
}

type ShadowsocksOutboundConfigurationObject_ServerObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port     uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Method   string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // Method
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Level    uint32 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) Reset() {
	*x = ShadowsocksOutboundConfigurationObject_ServerObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksOutboundConfigurationObject_ServerObject) ProtoMessage() {}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksOutboundConfigurationObject_ServerObject.ProtoReflect.Descriptor instead.
func (*ShadowsocksOutboundConfigurationObject_ServerObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksOutboundConfigurationObject_ServerObject) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type StreamSettingsObject_SockoptObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mark        uint32 `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	TcpFastOpen bool   `protobuf:"varint,2,opt,name=tcpFastOpen,proto3" json:"tcpFastOpen,omitempty"`
	Tproxy      string `protobuf:"bytes,3,opt,name=tproxy,proto3" json:"tproxy,omitempty"`
}

func (x *StreamSettingsObject_SockoptObject) Reset() {
	*x = StreamSettingsObject_SockoptObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_shadowsocks_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamSettingsObject_SockoptObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSettingsObject_SockoptObject) ProtoMessage() {}

func (x *StreamSettingsObject_SockoptObject) ProtoReflect() protoreflect.Message {
	mi := &file_model_shadowsocks_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSettingsObject_SockoptObject.ProtoReflect.Descriptor instead.
func (*StreamSettingsObject_SockoptObject) Descriptor() ([]byte, []int) {
	return file_model_shadowsocks_proto_rawDescGZIP(), []int{4, 0}
}

func (x *StreamSettingsObject_SockoptObject) GetMark() uint32 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *StreamSettingsObject_SockoptObject) GetTcpFastOpen() bool {
	if x != nil {
		return x.TcpFastOpen
	}
	return false
}

func (x *StreamSettingsObject_SockoptObject) GetTproxy() string {
	if x != nil {
		return x.Tproxy
	}
	return ""
}

var File_model_shadowsocks_proto protoreflect.FileDescriptor

var file_model_shadowsocks_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f,
	0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x25,
	0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x49, 0x6e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0x9d, 0x02, 0x0a, 0x26, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x54, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x4f,
	0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x1a, 0x9c, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22,
	0xcc, 0x01, 0x0a, 0x22, 0x44, 0x6f, 0x6b, 0x6f, 0x64, 0x65, 0x6d, 0x6f, 0x49, 0x6e, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x86,
	0x01, 0x0a, 0x22, 0x46, 0x72, 0x65, 0x65, 0x64, 0x6f, 0x6d, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xf8, 0x04, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x74, 0x6c, 0x73, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x0b, 0x74, 0x6c, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x36,
	0x0a, 0x0b, 0x74, 0x63, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0b, 0x74, 0x63, 0x70, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x36, 0x0a, 0x0b, 0x6b, 0x63, 0x70, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x0b, 0x6b, 0x63, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x34,
	0x0a, 0x0a, 0x77, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0a, 0x77, 0x73, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x38,
	0x0a, 0x0c, 0x71, 0x75, 0x69, 0x63, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0c, 0x71, 0x75, 0x69, 0x63,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x64, 0x73, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x0a, 0x64, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x43,
	0x0a, 0x07, 0x73, 0x6f, 0x63, 0x6b, 0x6f, 0x70, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x53, 0x6f, 0x63,
	0x6b, 0x6f, 0x70, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x73, 0x6f, 0x63, 0x6b,
	0x6f, 0x70, 0x74, 0x1a, 0x5d, 0x0a, 0x0d, 0x53, 0x6f, 0x63, 0x6b, 0x6f, 0x70, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x63, 0x70, 0x46,
	0x61, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74,
	0x63, 0x70, 0x46, 0x61, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_model_shadowsocks_proto_rawDescOnce sync.Once
	file_model_shadowsocks_proto_rawDescData = file_model_shadowsocks_proto_rawDesc
)

func file_model_shadowsocks_proto_rawDescGZIP() []byte {
	file_model_shadowsocks_proto_rawDescOnce.Do(func() {
		file_model_shadowsocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_shadowsocks_proto_rawDescData)
	})
	return file_model_shadowsocks_proto_rawDescData
}

var file_model_shadowsocks_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_model_shadowsocks_proto_goTypes = []interface{}{
	(*ShadowsocksInboundConfigurationObject)(nil),               // 0: model.ShadowsocksInboundConfigurationObject
	(*ShadowsocksOutboundConfigurationObject)(nil),              // 1: model.ShadowsocksOutboundConfigurationObject
	(*DokodemoInboundConfigurationObject)(nil),                  // 2: model.DokodemoInboundConfigurationObject
	(*FreedomOutboundConfigurationObject)(nil),                  // 3: model.FreedomOutboundConfigurationObject
	(*StreamSettingsObject)(nil),                                // 4: model.StreamSettingsObject
	(*ShadowsocksOutboundConfigurationObject_ServerObject)(nil), // 5: model.ShadowsocksOutboundConfigurationObject.ServerObject
	(*StreamSettingsObject_SockoptObject)(nil),                  // 6: model.StreamSettingsObject.SockoptObject
	(*any.Any)(nil), // 7: google.protobuf.Any
}
var file_model_shadowsocks_proto_depIdxs = []int32{
	5, // 0: model.ShadowsocksOutboundConfigurationObject.servers:type_name -> model.ShadowsocksOutboundConfigurationObject.ServerObject
	7, // 1: model.StreamSettingsObject.tlsSettings:type_name -> google.protobuf.Any
	7, // 2: model.StreamSettingsObject.tcpSettings:type_name -> google.protobuf.Any
	7, // 3: model.StreamSettingsObject.kcpSettings:type_name -> google.protobuf.Any
	7, // 4: model.StreamSettingsObject.wsSettings:type_name -> google.protobuf.Any
	7, // 5: model.StreamSettingsObject.httpSettings:type_name -> google.protobuf.Any
	7, // 6: model.StreamSettingsObject.quicSettings:type_name -> google.protobuf.Any
	7, // 7: model.StreamSettingsObject.dsSettings:type_name -> google.protobuf.Any
	6, // 8: model.StreamSettingsObject.sockopt:type_name -> model.StreamSettingsObject.SockoptObject
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_model_shadowsocks_proto_init() }
func file_model_shadowsocks_proto_init() {
	if File_model_shadowsocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_shadowsocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksInboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksOutboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DokodemoInboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreedomOutboundConfigurationObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamSettingsObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowsocksOutboundConfigurationObject_ServerObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_shadowsocks_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamSettingsObject_SockoptObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_shadowsocks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_shadowsocks_proto_goTypes,
		DependencyIndexes: file_model_shadowsocks_proto_depIdxs,
		MessageInfos:      file_model_shadowsocks_proto_msgTypes,
	}.Build()
	File_model_shadowsocks_proto = out.File
	file_model_shadowsocks_proto_rawDesc = nil
	file_model_shadowsocks_proto_goTypes = nil
	file_model_shadowsocks_proto_depIdxs = nil
}
